#!/bin/bash
set -x
IFS=$'\n'

export DISPLAY_ENV
export DISPLAYS=()

displ_home=(DP-1 DP-2 eDP-1)

DISPLAYS=($(xrandr --listmonitors | awk 'NR>1{ a[$NF] } END { n=asorti(a,sorted);for(i=1;i<=n;i++) print sorted[i] }'))

if [ "$(printf '%s\n' "${displ_home[*]}"|sort)" = "${DISPLAYS[*]}" ] ; then
  xrandr --output ${displ_home[0]} --mode 1920x1080 --pos 0x0    --rotate normal \
         --output ${displ_home[1]} --mode 1920x1080 --pos 1920x0 --rotate normal --primary \
         --output ${displ_home[2]} --mode 1920x1080 --pos 3840x0 --rotate normal 
  DISPLAY_ENV=home
fi
