#!/bin/sh
#
# Executed by startx (run your window manager from here)

# fix fonts
#systemd-run --user --on-calendar '*:*:0/5' /home/sysadm/.local/bin/fontsfix
pgrep -x fontsfix >/dev/null || fontsfix &

# start vbox services
command -v VBoxClient-all && $_

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# load fonts
for dir in $(find $XDG_DATA_HOME/fonts/ -type d) ; do 
  xset +fp $dir
done
xset fp rehash

# source files
[ -f /etc/xprofile ] && . /etc/xprofile
[ -f $XDG_CONFIG_HOME/x11/xprofile ] && . $XDG_CONFIG_HOME/x11/xprofile
[ -f $XDG_CONFIG_HOME/x11/xresources ] && xrdb -merge -I$HOME $XDG_CONFIG_HOME/x11/xresources
[ -f $XDG_CONFIG_HOME/x11/xmodmap ] && xmodmap $XDG_CONFIG_HOME/x11/xmodmap
[ -f $XDG_CONFIG_HOME/x11/setxrandr ] && . $XDG_CONFIG_HOME/x11/setxrandr

# set cursor
command -v xsetroot && pgrep -x $_ || $_ -cursor_name left_ptr

# turn on numlock
command -v numlockx && pgrep -x $_ || $_ &

# start notification manager
command -v dunst    && pgrep -x $_ || $_ &

# set wallpaper
command -v nitrogen && pgrep -x $_ || $_ --restore &

# start compositor
command -v picom    && pgrep -x $_ || $_ -f &

# start urxvt daemon
command -v urxvtd   && pgrep -x $_ || $_ &

# start bspwm window manager
exec bspwm 

