# vi: ft=tmux
###########################################################################

# tmux-tpad

set -g @tpad-vifm-bind          "C-v"
set -g @tpad-vifm-style         "fg=colour8"
set -g @tpad-vifm-height        "80%"
set -g @tpad-vifm-width         "80%"
set -g @tpad-vifm-dir           "#{pane_current_path}"
set -g @tpad-vifm-cmd           "vifm $PWD $PWD"
