#!/bin/sh

alias gs='git status'
alias ga='git add'
alias gaa='git add --all'
alias gau='git add -u'
alias gp='git push'
alias gpo='git push origin'
alias gtd='git tag --delete'
alias gtdr='git tag --delete origin'
alias gr='git branch -r'
alias gplo='git pull origin'
alias gb='git branch '
alias gc='git commit -m'
alias gco='git checkout '
alias gl='git log --oneline --graph'
alias gr='git remote'
alias grs='git remote show'
alias glo='git log --pretty="oneline"'
alias glol='git log --graph --oneline --decorate'
alias lg='lazygit'
