### Editing /etc/systemd/system/paccache.service.d/override.conf
### Anything between here and the comment below will become the new contents of the file

ExecStart=/usr/bin/paccache -rk2

### Lines below this comment will be discarded

### /etc/systemd/system/paccache.service
# [Unit]
# Description=Discard unused packages
#
# [Service]
# Type=oneshot
# ExecStart=/usr/bin/paccache -r
