packages:
  common:
    - docx2txt
    - feh
    - inkscape
    - poppler
    - qutebrowser
    - vifm
  pacman:
    - zathura
    - zathura-pdf-poppler
    - dumptorrent
    - fuse-zip
    - fuseiso
