#!/usr/bin/env bash

if command -v checkupdates &>/dev/null; then
  updates=$(checkupdates)

  if [[ -z "$(echo "$updates" | tr -d '[:space:]')" ]]; then
    updates_fmt=""
    color="#{{ .Vars.color.fg.darkest }}"
  else
    count="$(echo "$updates" | wc -l)"
    updates_fmt="$(echo "$updates" | awk 1 ORS='\\n' | sed 's/\\n$//')"
    color="#{{ .Vars.color.blue.bright }}"
  fi

  echo "{\"text\": \"<span color='$color'>󰮯</span> $count\", \"tooltip\": \"$updates_fmt\"}"
else
  echo "{\"text\": \"<span color='#{{ .Vars.color.fg.darkest }}'>󰮯</span> n/a\"}"
fi
