packages:
  common:
    - direnv
    - docker
    - gopls
    - kubectl
    - kubectx
    - mise
    - pyright
    - terraform
    - uv
  brew:
    - hashicorp/tap/terraform
    - kubecolor
    - pipenv
  pacman:
    - python-pipenv
