require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.theme"
require "user.various"

-- plugins
require "user.lsp"
require "user.plugins.cmp"
require "user.plugins.telescope"
require "user.plugins.gitsigns"
require "user.plugins.treesitter"
require "user.plugins.autopairs"
require "user.plugins.comment"
require "user.plugins.nvim-tree"
-- require "user.toggleterm"
-- require "user.project"
-- require "user.impatient"
-- require "user.indentline"
-- require "user.alpha"
require "user.plugins.whichkey"
-- require "user.autocommands"
require "user.plugins.tmux"
require "user.plugins.registers"
