require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.theme"

-- plugins
require "user.lsp"
require "user.plugins.cmp"
-- require "user.telescope"
require "user.plugins.gitsigns"
require "user.plugins.treesitter"
require "user.plugins.autopairs"
require "user.plugins.comment"
-- require "user.nvim-tree"
-- require "user.bufferline"
-- require "user.lualine"
-- require "user.toggleterm"
-- require "user.project"
-- require "user.impatient"
-- require "user.indentline"
-- require "user.alpha"
-- require "user.whichkey"
-- require "user.autocommands"
require "user.plugins.tmux"
require "user.plugins.registers"
