# vi: ft=tmux
###########################################################################
# plugins
#
# Hit prefix + I to install plugins
set -g @plugin 'tmux-plugins/tpm'                       # Tmux Plugin Manager
set -g @plugin 'sainnhe/tmux-fzf'                       # Manage tmux with fzf
set -g @plugin 'tmux-plugins/tmux-logging'              # Logging plugin for tmux
set -g @plugin 'nhdaly/tmux-better-mouse-mode'          # Better mouse management
set -g @plugin 'tmux-plugins/tmux-open'                 # o to open, C-o to open in editor, S-s to open in search engine
set -g @plugin 'Morantron/tmux-fingers'                 # Mouse selection and copy/paste
set -g @plugin 'Subbeh/tmux-tpad'                       # Floating window manager

set -g @logging-path "$HOME/.cache/tmux"                # Directory for logs created by tmux-logging
set -g @emulate-scroll-for-no-mouse-alternate-buffer "on"

###########################################################################
# tpad

set -g @tpad-debug              true

set -g @tpad-scratchpad-bind    "C-p"
set -g @tpad-scratchpad-style   "fg=colour5"
set -g @tpad-scratchpad-height  "80%"
set -g @tpad-scratchpad-width   "80%"
set -g @tpad-scratchpad-opts    "status on"
set -g @tpad-scratchpad-dir     "#{pane_current_path}"

set -g @tpad-notes-bind         "C-n"
set -g @tpad-notes-style        "fg=colour6"
set -g @tpad-notes-height       "80%"
set -g @tpad-notes-width        "80%"
set -g @tpad-notes-dir          "${XDG_NOTES_DIR}"
set -g @tpad-notes-cmd          "nvim -c NvimTreeOpen"

###########################################################################
# misc

set -g @scroll-speed-num-lines-per-scroll 5
set -g @open-S 'https://www.google.com/search?q='
set -g @fingers-key F
set -g @fingers-jump-key N
