# vi: ft=tmux
###########################################################################
# theme
set -g message-style                "fg=colour0,  bg=colour4,bold"
set -g message-command-style        "fg=colour0,  bg=colour4,bold"

set -g pane-active-border           "fg=colour5,  bg=terminal"
set -g pane-border-style            "fg=colour238,bg=terminal"

set -g status                       "on"
set -g status-justify               centre
set -g status-position              top
set -g status-interval              10
set -g status-left-length           50
set -g status-left                  "#[bold]#{?#(__tmux_is_remote #{client_pid}),#[bg=colour9]#[fg=colour238] 󰀦 remote [#(hostname)] 󰀦 #[bg=terminal]#[fg=colour243] ⏽ }#[fg=terminal,bg=terminal]#{session_name}[#[fg=colour12]#{server_sessions}#[fg=terminal]] #[fg=colour5] #[fg=terminal,bg=terminal]"
set -g status-right                 "#(__tmux_status_right '#{pane_current_path}')"
set -g status-style                 "fg=terminal,bg=terminal"

set -g window-style                 "fg=colour243,bg=terminal"
set -g window-active-style          "fg=terminal,bg=terminal"
set -g window-status-activity-style "fg=terminal,bg=colour12,bold"
set -g window-status-style          "fg=colour239,bg=colour12"
set -g window-status-separator      "#[fg=colour243] ⏽ "
set -g window-status-format         "#[bg=terminal,fg=colour243][#[fg=colour4,bold]#I#[fg=colour243,nobold]]#W#{@jpro_status}"
set -g window-status-current-format "#[bold]#{?window_zoomed_flag,#[bg=#fab387]  #W#{@jpro_status} ,#[fg=colour12]#[bg=terminal] #[fg=terminal]#W#{@jpro_status}#[nobold]}"

set-hook -g client-focus-in         "set window-active-style 'fg=terminal,bg=terminal'"
set-hook -g client-focus-out        "set window-active-style 'fg=colour243,bg=terminal'"

# Periodically update jpro status (macOS only)
if-shell 'test "$PROFILE_OS" = "darwin" && test -x ~/.local/bin/__tmux_jpro_status_daemon' \
  "run-shell -b '~/.local/bin/__tmux_jpro_status_daemon'"

