# ~/.tmux.conf

set -g default-terminal "screen-256color"    # Set the default terminal mode to 256color mode
set -g prefix C-s                            # Setting the prefix from C-b to C-a
set -g mouse off                             # mouse support - set to on if you want to use the mouse
set -s escape-time 1                         # Setting the delay between prefix and command
set -g base-index 1                          # Set the base index for windows to 1 instead of 0
setw -g mode-keys vi                         # enable vi keys.
setw -g pane-base-index 1                    # Set the base index for panes to 1 instead of 0

bind q set-option status                     # toggle status line
bind C-a set-window-option synchronize-panes # shortcut for synchronize-panes toggle
bind C-s send-prefix                         # Ensure that we can send Ctrl-s to other apps
unbind C-b                                   # Free the original Ctrl-b prefix keybinding

bind \\ split-window -h                      # split panes vertically
bind - split-window -v                       # split panes horizontally
bind _ split-window -v -c "#{pane_current_path}" # split and retain current directory of existing pane
bind | split-window -h -c "#{pane_current_path}" # split and retain current directory of existing pane

bind h select-pane -L                        # move to left pane
bind j select-pane -D                        # move to pane below
bind k select-pane -U                        # move to pane above
bind l select-pane -R                        # move to right pane

bind -r C-l select-window -t :+              # move to next window
bind -r C-h select-window -t :-              # move to previous window

bind -r H resize-pane -L 2                   # resize pane left
bind -r J resize-pane -D 2                   # resize pane down
bind -r K resize-pane -U 2                   # resize pane up
bind -r L resize-pane -R 2                   # resize pane right

bind P pipe-pane -o "cat >>~/#W.log" \; display "Toggled logging to ~/#W.log" # Log output to a text file on demand

# map vim keys for copy-mode
bind Escape copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
unbind p
bind p paste-buffer
bind C-v run "tmux set-buffer \"$(xclip -o -sel clipboard)\"; tmux paste-buffer"

# reload config
unbind F5
bind F5 \
    source-file ~/.config/tmux/tmux.conf \;\
    display 'Reloaded tmux config'

# plugins
set -g @plugin 'tmux-plugins/tpm'            # load tpm plugin
set -g @plugin 'tmux-plugins/tmux-resurrect' # load resurrect plugin
run '~/.config/tmux/plugins/tpm/tpm'         # run tpm plugin

# theme
setw -g pane-border-style fg=blue,bg=black           # colors for pane borders
setw -g pane-active-border-style fg=magenta,bg=black # colors for active pane borders

set -g status-style fg=white,bg=black                # set the status line's colors
set -g message-style fg=white,bold,bg=black          # command / message line
set -g status-interval 10                            # Update the status line every x seconds

set -g status-justify centre                         # Center the window list in the status line
setw -g window-status-style fg=white,bg=black        # set the color of the window list
setw -g window-status-current-style fg=blue,bold,bg=black # set colors for the active window

set -g status-left-length 40                         # left status line length
set -g status-left "#[fg=blue,bold]Session: #S #[fg=white]#I #[fg=red]#P" # left status line

set -g status-right "#[fg=white]%d %b %R"            # status line right side

set -g visual-activity on                            # enable visual alerts
setw -g monitor-activity on                          # enable activity alerts
setw -g window-status-activity-style fg=white,bg=red # activity alert style
