# ~/.tmux.conf

# Set the default terminal mode to 256color mode
set -g default-terminal "screen-256color"

# Setting the prefix from C-b to C-a
set -g prefix C-s

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
run '~/.config/tmux/plugins/tpm/tpm'

# enable vi keys.
setw -g mode-keys vi

# map vim keys for copy-mode
bind Escape copy-mode
# bind -t vi-copy v begin-selection
bind -T copy-mode-vi v begin-selection
# bind -t vi-copy y copy-pipe "xclip -sel clip -i"
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
unbind p
bind p paste-buffer
bind C-v run "tmux set-buffer \"$(xclip -o -sel clipboard)\"; tmux paste-buffer"

# shortcut for synchronize-panes toggle
bind C-a set-window-option synchronize-panes

# Ensure that we can send Ctrl-s to other apps
bind C-s send-prefix

# Free the original Ctrl-b prefix keybinding
unbind C-b

# Setting the delay between prefix and command
set -s escape-time 1

# Set the base index for panes to 1 instead of 0
setw -g pane-base-index 1

# Set the base index for windows to 1 instead of 0
set -g base-index 1

# Reload config
unbind F5
bind F5 \
    source-file ~/.config/tmux/tmux.conf \;\
    display 'Reloaded tmux config'

# splitting panes with | and -
bind \\ split-window -h
bind - split-window -v

# split pane and retain the current directory of existing pane
bind _ split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"

# moving between panes with Prefix h,j,k,l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Quick window selection
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Pane resizing panes with Prefix H,J,K,L
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# mouse support - set to on if you want to use the mouse
set -g mouse off

# Log output to a text file on demand
bind P pipe-pane -o "cat >>~/#W.log" \; display "Toggled logging to ~/#W.log"

# set the status line's colors
set -g status-style fg=white,bg=black

# set the color of the window list
setw -g window-status-style fg=white,bg=black

# set colors for the active window
setw -g window-status-current-style fg=blue,bold,bg=black

# colors for pane borders
setw -g pane-border-style fg=blue,bg=black
setw -g pane-active-border-style fg=magenta,bg=black

# Command / message line
set -g message-style fg=white,bold,bg=black

# Status line left side to show Session:window:pane
set -g status-left-length 40
set -g status-left "#[fg=blue,bold]Session: #S #[fg=white]#I #[fg=red]#P"

# Status line right side - 31-Oct 13:37
set -g status-right "#[fg=white]%d %b %R"

# Update the status line every x seconds
set -g status-interval 10

# Center the window list in the status line
set -g status-justify centre

# enable activity alerts
setw -g monitor-activity on
set -g visual-activity on
setw -g window-status-activity-style fg=white,bg=red
