
# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

# vi mode in copy-mode
set-window-option -g mode-keys vi

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ${XDG_CONFIG_HOME}/tmux/tmux.conf

# enable copy-paste
bind C-S-c run "tmux save-buffer - | xclip -i -sel clipboard"
bind C-S-v run "tmux set-buffer \"$(xclip -o -sel clipboard)\"; tmux paste-buffer"

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off

# list of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# load theme
#set -g @plugin 'wfxr/tmux-power'
#set -g @tmux_power_theme 'sky'

set -g @plugin "arcticicestudio/nord-tmux"
set -g @nord_tmux_no_patched_font "1"

#set -g @plugin 'dracula/tmux'
#set -g @plugin 'jimeh/tmux-themepack'
#set -g @themepack 'powerline/block/cyan'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '${XDG_CONFIG_HOME}/tmux/plugins/tpm/tpm'
