#!/bin/zsh

bindkey -v
bindkey -m 2>/dev/null

# See: https://wiki.archlinux.org/title/Zsh#Key_bindings
# create a zkbd compatible hash;
# to add other keys to this hash, see: man 5 terminfo
typeset -g -A key

key[Home]="${terminfo[khome]}"
key[End]="${terminfo[kend]}"
key[Insert]="${terminfo[kich1]}"
key[Backspace]="${terminfo[kbs]}"
key[Delete]="${terminfo[kdch1]}"
key[Up]="${terminfo[kcuu1]}"
key[Down]="${terminfo[kcud1]}"
key[Left]="${terminfo[kcub1]}"
key[Right]="${terminfo[kcuf1]}"
key[PageUp]="${terminfo[kpp]}"
key[PageDown]="${terminfo[knp]}"
key[ShiftTab]="${terminfo[kcbt]}"

# setup key accordingly
[[ -n "${key[Home]}"          ]] && bindkey -- "${key[Home]}"          beginning-of-line
[[ -n "${key[End]}"           ]] && bindkey -- "${key[End]}"           end-of-line
[[ -n "${key[Insert]}"        ]] && bindkey -- "${key[Insert]}"        overwrite-mode
[[ -n "${key[Backspace]}"     ]] && bindkey -- "${key[Backspace]}"     backward-delete-char
[[ -n "${key[Delete]}"        ]] && bindkey -- "${key[Delete]}"        delete-char
[[ -n "${key[Up]}"            ]] && bindkey -- "${key[Up]}"            up-line-or-beginning-search
[[ -n "${key[Down]}"          ]] && bindkey -- "${key[Down]}"          down-line-or-beginning-search
[[ -n "${key[Left]}"          ]] && bindkey -- "${key[Left]}"          backward-char
[[ -n "${key[Right]}"         ]] && bindkey -- "${key[Right]}"         forward-char
[[ -n "${key[PageUp]}"        ]] && bindkey -- "${key[PageUp]}"        beginning-of-buffer-or-history
[[ -n "${key[PageDown]}"      ]] && bindkey -- "${key[PageDown]}"      end-of-buffer-or-history
[[ -n "${key[ShiftTab]}"      ]] && bindkey -- "${key[ShiftTab]}"      reverse-menu-complete

# Modifier prefixes for bindkey sequences:
#   ^x  / \C-x   Ctrl+X       (letters case-insensitive: ^A == ^a)
#   \ex / ^[x    Alt/Meta+x   (Esc-prefix form; ^[ is Escape)
#   \eX / ^[X    Alt+Shift+X
#   ^[^X / \e^x  Ctrl+Alt+X   (Esc then Ctrl+X)
#   \M-x         Meta+x       (8-bit meta; prefer \ex on modern terminals)
# Special: ^I Tab, ^M Enter, ^[ Esc, ^? Backspace, ^ /^@ Ctrl+Space
# Discover a key's sequence at the prompt with Ctrl+V then the key combo.
bindkey '^[q'     push-input          # Esc+Q
bindkey '^A'      beginning-of-line
bindkey '^E'      end-of-line
bindkey '^Z'      fancy-ctrl-z
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word
bindkey '^[t'     transpose-words

bindkey -M vicmd '^[q'     push-line
bindkey -M vicmd '^A'      beginning-of-line
bindkey -M vicmd '^E'      end-of-line
bindkey -M vicmd '^[[1;5C' forward-word
bindkey -M vicmd '^[[1;5D' backward-word
bindkey -M vicmd '^[t'     transpose-words
bindkey -M vicmd '^v'      edit-command-line

# Finally, make sure the terminal is in application mode, when zle is
# active. Only then are the values from $terminfo valid.
if (( ${+terminfo[smkx]} && ${+terminfo[rmkx]} )); then
    autoload -Uz add-zle-hook-widget
    function zle_application_mode_start { echoti smkx }
    function zle_application_mode_stop { echoti rmkx }
    add-zle-hook-widget -Uz zle-line-init zle_application_mode_start
    add-zle-hook-widget -Uz zle-line-finish zle_application_mode_stop
fi

# History navigation
autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search down-line-or-beginning-search

# Edit current command in $EDITOR. From: https://unix.stackexchange.com/a/6622
autoload edit-command-line
zle -N edit-command-line

# Vi-mode
autoload -U select-word-style
zle -N select-word-style
select-word-style normal
zstyle :zle:transpose-words word-style shell

function zle-keymap-select() {
  case $KEYMAP in
    vicmd) echo -ne '\e[2 q' ;;        # steady block
    viins | main) echo -ne '\e[6 q' ;; # steady line
  esac
  zle reset-prompt
}
zle -N zle-keymap-select

function zle-line-init() {
  zle -K viins
}
zle -N zle-line-init

function fancy-ctrl-z() {
  if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line -w
  else
    zle push-input -w
    zle clear-screen -w
  fi
}
zle -N fancy-ctrl-z
