# vi: ft=tmux
###########################################################################

# tmux-tpad

set -g @tpad-yazi-bind          "C-y"
set -g @tpad-yazi-style         "fg=colour7"
set -g @tpad-yazi-height        "80%"
set -g @tpad-yazi-width         "80%"
set -g @tpad-yazi-per-dir       "window"
set -g @tpad-yazi-opts          "status on"
set -g @tpad-yazi-dir           "#{pane_current_path}"
set -g @tpad-yazi-cmd           'yazi'
