-- stylua: ignore start
hl.env("CLUTTER_BACKEND",                     "wayland")
hl.env("GDK_BACKEND",                         "wayland")
hl.env("GLFW_IM_MODULE",                      "ibus")
hl.env("LIBVA_DRIVER_NAME",                   "iHD")
hl.env("MOZ_ENABLE_WAYLAND",                  "1")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR",         "1.25")
hl.env("QT_QPA_PLATFORMTHEME",                "qt6ct")
hl.env("QT_QPA_PLATFORM",                     "wayland")
hl.env("QT_QPA_PLATFORM",                     "wayland")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("SDL_VIDEODRIVER",                     "wayland")
hl.env("XDG_CURRENT_DESKTOP",                 "Hyprland")
hl.env("XDG_SESSION_DESKTOP",                 "Hyprland")
hl.env("XDG_SESSION_TYPE",                    "wayland")
