hl.on("hyprland.start", function()
  hl.dispatch(hl.dsp.focus({ workspace = "2" }))
  hl.exec_cmd("systemctl --user start hyprland-session.target")
  hl.exec_cmd("systemctl --user enable --now hyprpolkitagent.service")
  hl.exec_cmd("__hypr_tmux_sessions")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  hl.exec_cmd("hyprpaper")
  hl.exec_cmd("swaync")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("Thunar --daemon")
  hl.exec_cmd("kitty --hold __hypr_tmux_sessions", { workspace = "special:term silent" })
  hl.exec_cmd("firefox-default.desktop", { workspace = "2" })
end)

hl.on("hyprland.shutdown", function()
  os.execute("systemctl --user stop hyprland-session.target && sleep 0.1")
end)
