#! /bin/sh

sxhkd &
picom &
$HOME/.config/polybar/launch.sh

if [ -n "$DISPLAY_ENV" ] ; then
  bspc monitor DP-1 -d 5 6 7 8
  bspc monitor DP-2 -d 1 2 3 4
  bspc monitor eDP-1 -d 9
fi

bspc monitor -d 1 2 3 4
bspc config border_width 0 
bspc config window_gap  12
bspc config top_padding 24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Window state configs
bspc rule -a alsamixer state=floating focus=on
bspc rule -a Nitrogen state=floating focus=on
bspc rule -a Pavucontrol state=floating focus=on center=on
bspc rule -a firefox state=floating follow=on
bspc rule -a Brave-browser state=floating follow=on
bspc rule -a URxvt:scratchy sticky=on state=floating rectangle=widthxheight+Xoffset+Yoffset
bspc config external_rules_command "$HOME/.local/bin/bspwm-external-rules"

floating_noborder

# Mouse bindings
bspc config pointer_modifier shift

#   Set mouse 1 to move floating windows
bspc config pointer_action1 move

#   Mouse 2 button resizes the window by side
bspc config pointer_action2 resize_side

#   Mouse 3 button (right mouse) resize by corner
bspc config pointer_action2 resize_corner



