#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
killall polybar 2>/dev/null
$HOME/.config/polybar/launch.sh 2> ${XDG_CACHE_HOME}/.polybar.err &

bspc monitor -d 1 2 3 4

bspc config border_width         0 
bspc config window_gap           12
bspc config top_padding          22
bspc config bottom_padding       10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true

bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config focus_follows_pointer     true

# Window state configs
bspc rule -a alsamixer            state=floating focus=on follow=on
bspc rule -a Arandr               state=floating focus=on follow=on
bspc rule -a Nitrogen             state=floating focus=on follow=on
bspc rule -a Pavucontrol          state=floating focus=on follow=on
bspc rule -a firefox              state=floating focus=on follow=on
bspc rule -a Brave-browser        state=floating focus=on follow=on
bspc rule -a Chromium             state=floating focus=on follow=on
bspc rule -a Galculator           state=floating focus=on follow=on
bspc rule -a feh                  state=floating focus=on follow=on
bspc rule -a Popcorn-Time         state=floating focus=on follow=on
bspc rule -a burp-StartBurp       state=floating focus=on follow=on
bspc rule -a vlc                  state=floating focus=on follow=on
bspc rule -a mpv                  state=floating focus=on follow=on
bspc rule -a Cheese               state=floating focus=on follow=on
bspc rule -a Cherrytree           state=floating focus=on follow=on
bspc rule -a Thunar               state=floating focus=on follow=on
bspc rule -a qBittorrent          state=floating focus=on follow=on
bspc rule -a Virt-manager         state=floating focus=on follow=on
bspc rule -a 'VirtualBox Manager' state=floating focus=on follow=on
bspc rule -a 'VirtualBox Machine' state=floating focus=on follow=on
bspc rule -a 'Org.gnome.Nautilus' state=floating focus=on follow=on

bspc config external_rules_command "${XDG_CONFIG_HOME}/bspwm/bspwm-external-rules"

# Mouse bindings
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

# Multi monitor config
if [[ "$DISPLAY_ENV" -eq "home" ]] ; then
  bspc monitor DP-1 -d  0
  bspc monitor DP-2 -d  1 2 3 4
  bspc monitor eDP-1 -d 5

  bspc config -m DP-1 top_padding 0
  bspc config -m DP-1 bottom_padding 0
  bspc config -m eDP-1 top_padding 0
  bspc config -m eDP-1 bottom_padding 0

  bspc rule -a firefox            monitor='DP-1'
fi
