#!/bin/sh
set -x

if [[ "$(xrandr --current | awk '/ connected/ { print $1 }' | sort)" == DP1* ]]; then
	export DISPL_LT=eDP1
	export DISPL_L=DP1-2
	export DISPL_M=DP1-3
else
	export DISPL_LT=eDP1
	export DISPL_L=DP2-2
	export DISPL_M=DP2-3
fi

pgrep -x nitrogen || nitrogen --restore &
pgrep -x picom >/dev/null || picom &
pgrep -x sxhkd >/dev/null || sxhkd &
pgrep -x dunst || dunst &

# Set desktops on first load
[ "$1" = 0 ] && bspc monitor -d 0 1 2 3 4 5

bspc config border_width 0
bspc config window_gap 12
bspc config top_padding 20
bspc config bottom_padding 10

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config single_monocle true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config focus_follows_pointer true

# Window state config
bspc rule -a alsamixer state=floating focus=on follow=on
bspc rule -a Arandr state=floating focus=on follow=on
bspc rule -a Nitrogen state=floating focus=on follow=on
bspc rule -a Pavucontrol state=floating focus=on follow=on
bspc rule -a Galculator state=floating focus=on follow=on
bspc rule -a feh state=floating focus=on follow=on
bspc rule -a Thunar state=floating focus=on follow=on
bspc rule -a qBittorrent state=floating focus=on follow=on
bspc rule -a Virt-manager state=floating focus=on follow=on
bspc rule -a scrcpy state=floating focus=on follow=on
bspc rule -a VirtualBox state=floating focus=on follow=on
bspc rule -a 'VirtualBox Manager' state=floating focus=on follow=on
bspc rule -a 'VirtualBox Machine' state=floating focus=on follow=on
bspc rule -a 'Org.gnome.Nautilus' state=floating focus=on follow=on
bspc rule -a Spotify -o monitor="eDP-1"

# Load external rules (mainly for Spotify)
# bspc config external_rules_command "${XDG_CONFIG_HOME}/bspwm/bspwm-external-rules"

# Mouse bindings
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

# Set up monitors (docked or undocked) and launch Polybar
. bspwm_setup_monitors >"${XDG_CACHE_HOME}/bspwm.log" 2>&1 &

# Use monocle layout by default on all desktops
bspc query -D | xargs -I {} bspc desktop {} -l monocle

# Multi monitor config on first load
if [[ "$1" = 0 ]]; then
	if [[ "$DISPLAY_ENV" -eq "docked" ]]; then
		bspc rule -a Alacritty -o monitor="${DISPL_M:?not set}"
		for i in {1..5}; do test -e /tmp/tmux-1000/default && break || sleep 1; done
		alacritty --hold -e tmuxinator start infra &
		bspc rule -a firefox -o monitor="${DISPL_M:?not set}"
		firefox -P default &
		# bspc rule -a obsidian   -o monitor="${DISPL_L:?not set}"; obsidian "obsidian://open?vault=notes" &
	fi
fi
