targets:
  etc: /etc
packages:
  brew:
    # apps
    - alt-tab
    - clintmod/formulas/macprefs
    - dimentium/autoraise/autoraise
    - google-chrome
    - karabiner-elements
    - logi-options+
    - mackup
    - middleclick
    - mole
    - raycast
    # - rectangle
    - spotify
    - vlc
    # fonts
    - font-fira-code-nerd-font
    - font-fira-mono-nerd-font
    - font-hack-nerd-font
    - sf-symbols
