packages:
  brew:
    # apps
    - alt-tab
    - clintmod/formulas/macprefs
    - dimentium/autoraise/autoraise
    - google-chrome
    - karabiner-elements
    - logi-options+
    - middleclick
    - raycast
    - rectangle
    - spotify
    # fonts
    - font-fira-code-nerd-font
    - font-fira-mono-nerd-font
    - font-hack-nerd-font
