packages:
  common:
    - age
    - arp-scan
    - bat
    - btop
    - dialog
    - direnv
    - coreutils
    - duf
    - dust
    - ffmpeg
    - gawk
    - git
    - go
    - gron
    - htop
    - inetutils
    - iperf3
    - jq
    - lsof
    - man-db
    - mtr
    - ncdu
    - nmap
    - onefetch
    - openssh
    - shellcheck
    - socat
    - speedtest-cli
    - tldr
    - tree
    - unzip
    - vim
    - vivid
    - wget
    - whois
    - yq
  pacman:
    - less
    - npm
    - openbsd-netcat
    - pandoc-cli
    - sudo
  brew:
    - gnu-sed
    - node
    - pandoc
    - rar
    - watch
    - xh
