[color]

bg          = ${xrdb:background:#303030}
fg          = ${xrdb:foreground:#d7d7d7}
bar         = #cc303030
bar-light   = #aa303030
sep         = #3f5360

red         = ${xrdb:color1:#ff5f5f}
green       = ${xrdb:color2:#afd787}
yellow      = ${xrdb:color3:#d7d7af}
blue        = ${xrdb:color4:#87d7ff}
magenta     = ${xrdb:color5:#d7afd7}
cyan        = ${xrdb:color6:#87d7af}
;grey        = ${xrdb:color7:#626262}
grey        = #797979
black       = ${xrdb:color8:#444444}
white       = ${xrdb:color15:#d7d7d7}
