[global/wm]

include-file = ~/.config/polybar/colors.ini
include-file = ~/.config/polybar/modules.ini

[bar/main]
;bottom = false
;fixed-center = true

width = 100%

background = #00
foreground = ${color.fg}

font-0 = Misc Tamzen:14;3
font-1 = Wuncon Siji:size=12;3

;dim-value = 1.0
line-size = 3
line-color = ${color.blue}


;module-margin-right = 1

;border-color = ${color.bar}

wm-restack = bspwm

enable-ipc = true

[bar/top]
inherit = bar/main
height = 22
;border-size = 1
overline-color = ${color.green}
module-margin = 1
border-bottom-color = ${color.blue}
border-bottom-size = 2
modules-left = bspwm title
modules-center = date
modules-right = spotify spotify-prev spotify-play-pause spotify-next bluetooth pulseaudio-control nordvpn kbd_backlight lifx backlight powermenu

[bar/bottom]
inherit = bar/main
height = 17
bottom = true
background = #00
module-margin-right = 1
;border-top-size = 2
border-top-color = ${color.blue}
;overline-size = 2
overline-color = #f00
underline-size = 2
underline-color = #00f
modules-left = 
modules-center = checknet updates dot-status cpu memory battery
modules-right = 

[settings]
screenchange-reload = true
