[module/date]
type = custom/script
exec = $XDG_CONFIG_HOME/polybar/scripts/date/date.sh
tail = true
scroll-up = kill -USR1 %pid%
scroll-down = kill -USR2 %pid%
format = <label>

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/vpn]
type = custom/script
exec = $XDG_CONFIG_HOME/polybar/scripts/vpn/vpn.sh
click-left = kill -USR1 %pid%
click-right = notify-send "NordVPN Status" "$(nordvpn status)"
tail = true
format = <label>
format-padding = 0

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/lifx]
type = custom/script
exec = $XDG_CONFIG_HOME/polybar/scripts/lifx/lifx.sh
click-left = echo toggle > /tmp/lifx.pipe
scroll-up = echo up > /tmp/lifx.pipe
scroll-down = echo down > /tmp/lifx.pipe
tail = true
format = <label>

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/pomodoro]
type = custom/script
exec = $XDG_CONFIG_HOME/polybar/scripts/timer/pomodoro.sh
click-right = echo notify > /tmp/pomodoro.pipe &
click-left = echo toggle > /tmp/pomodoro.pipe &
click-middle = echo reset > /tmp/pomodoro.pipe &
tail = true
format = %{T3}<label>%{T-}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/sensors]
type = custom/script
exec = $XDG_CONFIG_HOME/polybar/scripts/sensors/sensors.sh
tail = true
format = <label>

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/checknet]
type = custom/script

; Available tokens:
;   %counter%
; Command to be executed (using "/usr/bin/env sh -c [command]")
exec = ~/.config/polybar/scripts/check-network

; Conditional command that, if defined, needs to exit successfully
; before the main exec command is invoked.
; Default: ""
;;exec-if = ""

; Will the script output continous content?
; Default: false
tail = true

; Seconds to sleep between updates
; Default: 2 (0 if `tail = true`)
interval = 5

; Available tags:
;   <output> - deprecated
;   <label> (default)
format = <label>
;format-prefix =

; Available tokens:
;   %output%
; Default: %output%
label = %output%

; Available tokens:
;   %counter%
;   %pid%
;
; "click-(left|middle|right)" will be executed using "/usr/bin/env sh -c [command]"
click-left = networkmanager_dmenu &
click-right = networkmanager_dmenu &
;;double-click-left = echo double left %counter%
;;double-click-middle = echo double middle %counter%
;;double-click-right = echo double right %counter%

; Available tokens:
;   %counter%
;   %pid%
;
; "scroll-(up|down)" will be executed using "/usr/bin/env sh -c [command]"
;;scroll-up = echo scroll up %counter%
;;scroll-down = echo scroll down %counter%

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/updates]
type = custom/script

; Available tokens:
;   %counter%
; Command to be executed (using "/usr/bin/env sh -c [command]")
exec = ~/.config/polybar/scripts/updates.sh

; Conditional command that, if defined, needs to exit successfully
; before the main exec command is invoked.
; Default: ""
;;exec-if = ""

; Will the script output continous content?
; Default: false
tail = true

; Seconds to sleep between updates
; Default: 2 (0 if `tail = true`)
;interval = 5

; Available tags:
;   <output> - deprecated
;   <label> (default)
format = <label>
format-prefix = 

; Available tokens:
;   %output%
; Default: %output%
label = %output%

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/sysmenu]
type = custom/text
content = 

content-foreground = ${color.fg}

click-left = ~/.config/polybar/scripts/powermenu.sh &

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/pulseaudio-control]
type = custom/script
tail = true
format-underline = ${colors.cyan}
label-padding = 2
label-foreground = ${colors.foreground}

# Icons mixed from Font Awesome 5 and Material Icons
# You can copy-paste your options for each possible action, which is more
# trouble-free but repetitive, or apply only the relevant ones (for example
# --sink-blacklist is only needed for next-sink).
exec = ~/.config/polybar/scripts/pulseaudio-control.sh --icons-volume " , " --icon-muted " " --sink-nicknames-from "device.description" --sink-nickname "alsa_output.usb-Sennheiser_Sennheiser_SC60_for_Lync_0000000000-00.analog-stereo:  Headset" --sink-nickname "alsa_output.pci-0000_00_1f.3.analog-stereo:  Built-in" listen
click-right = exec pavucontrol &
click-left = ~/.config/polybar/scripts/pulseaudio-control.sh togmute
click-middle = ~/.config/polybar/scripts/pulseaudio-control.sh --sink-blacklist "alsa_output.usb-DisplayLink_Dell_Universal_Dock_D6000_1801300418-02.iec958-stereo" next-sink
scroll-up = ~/.config/polybar/scripts/pulseaudio-control.sh --volume-max 130 up
scroll-down = ~/.config/polybar/scripts/pulseaudio-control.sh --volume-max 130 down

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/bluetooth]
type = custom/script
exec = rofi-bluetooth --status
interval = 1
click-left = rofi-bluetooth &
