# vi: ft=tmux
###########################################################################

# tmux-tpad

# lazygit
set -g @tpad-git-bind           "C-g"
set -g @tpad-git-style          "fg=colour3"
set -g @tpad-git-height         "80%"
set -g @tpad-git-width          "80%"
set -g @tpad-git-per-dir        "true"
set -g @tpad-git-cmd            "{ git rev-parse --is-inside-work-tree && exec lazygit; } || exit"
set -g @tpad-git-shell          "true"

# dash
set -g @tpad-dash-bind           "C-d"
set -g @tpad-dash-style          "fg=colour3"
set -g @tpad-dash-height         "80%"
set -g @tpad-dash-width          "80%"
set -g @tpad-dash-per-dir        "true"
set -g @tpad-dash-cmd            "{ git rev-parse --is-inside-work-tree && exec gh dash; } || exit"
set -g @tpad-dash-shell          "true"
