# vi: ft=tmux
###########################################################################

# tmux-tpad

set -g @tpad-agentmgr-bind        "C-c"
set -g @tpad-agentmgr-style       "fg=colour2"
set -g @tpad-agentmgr-height      "80%"
set -g @tpad-agentmgr-width       "80%"
set -g @tpad-agentmgr-cmd         "agent-manager"
set -g @tpad-agentmgr-opts        "status on"
