# vi: ft=tmux
###########################################################################

# tmux-tpad

set -g @tpad-task-bind          "C-t"
set -g @tpad-task-style         "fg=colour11"
set -g @tpad-task-height        "40%"
set -g @tpad-task-width         "40%"
set -g @tpad-task-cmd           "taskwarrior-tui"
