hl.on("hyprland.start", function()
  hl.dispatch(hl.dsp.focus({ workspace = "2" }))
  hl.exec_cmd("systemctl --user start hyprland-session.target")
  hl.exec_cmd("systemctl --user enable --now hyprpolkitagent.service")
  hl.exec_cmd("__hypr_tmux_sessions")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  hl.exec_cmd("swaync")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("Thunar --daemon")
  hl.exec_cmd("kitty --hold __tmuxinator_sessions", { workspace = "special:term silent" })
  hl.exec_cmd("firefox-default.desktop", { workspace = "2" })
  StartWaybar(Panel)
end)

hl.on("hyprland.shutdown", function()
  os.execute("systemctl --user stop hyprland-session.target && sleep 0.1")
end)

hl.on("monitor.added", Func.apply_outputs)
hl.on("monitor.removed", Func.apply_outputs)

hl.bind("switch:on:Lid Switch", function()
  Func.set_lid(true)
end)
hl.bind("switch:off:Lid Switch", function()
  Func.set_lid(false)
end)

-- Windows
hl.on("window.open", function()
  -- DynamicLayout()
end)
hl.on("window.destroy", function()
  -- DynamicLayout()
end)
hl.on("window.move_to_workspace", function()
  -- DynamicLayout()
end)
hl.on("window.fullscreen", function()
  -- DynamicLayout()
end)
hl.on("window.title", function(w)
  Func.bitwarden_float(w)
  -- DynamicLayout()
end)
