targets:
  etc: /etc
packages:
  pacman:
    # core
    - base
    - base-devel
    - btrfs-progs
    - dosfstools
    - efibootmgr
    - fprintd
    - grub
    - intel-ucode
    - libfido2
    - linux
    - linux-firmware
    - linux-headers
    - linux-lts
    - linux-lts-headers
    - openssh
    - os-prober
    - sbctl
    - snap-pac
    - snapper
    - systemd-ukify
    - tlp
    - zram-generator
    # network
    - dhcpcd
    - networkmanager
    - proton-vpn-cli
    # tools
    - go
    - jq
    - keyd
    - npm
    - reflector
    # misc
    - fwupd
    # sound
    - pavucontrol
    - pipewire
    - pipewire-pulse
    - sof-firmware
    - wireplumber
  aur:
    - paru
    - pam-fprint-grosshack
