packages:
  pacman:
    - age
    - base
    - base-devel
    - dhcpcd
    - git
    - go
    - grub
    - jq
    - less
    - linux
    - lsof
    - openssh
    - os-prober
    - reflector
    - vim
  aur:
    - yay
    - gnu-netcat
