# vi: ft=tmux
###########################################################################

# tmux-tpad

set -g @tpad-k9s-bind           "C-k"
set -g @tpad-k9s-style          "fg=colour4"
set -g @tpad-k9s-height         "80%"
set -g @tpad-k9s-width          "80%"
set -g @tpad-k9s-dir            "${XDG_HOMEOPS_DIR}"
set -g @tpad-k9s-cmd            "k9s"
