packages:
  pacman:
    - cliphist
    - hypridle
    - hyprland
    - hyprlock
    - hyprpaper
    - hyprpolkitagent
    - ttf-proggyclean-nerd
    - swaync
    - thunar
    - libnewt
    - waybar
    - xdg-desktop-portal-hyprland
    - flameshot
    - rofi
    - pipewire
    - wireplumber
    - qt5-wayland
    - qt6-wayland
    - noto-fonts
ignore:
  - .luacheckrc
  - .luarc.json
  - .stylua.toml
