#!/usr/bin/env bash

statemate=$(__statemate_status tmux)
git=$(gitmux "$1")

parts=()
[[ -n "$statemate" ]] && parts+=("$statemate")
[[ -n "$git" ]] && parts+=("$git")

sep=" #[fg=colour243]⏽#[fg=default] "
result=""
for part in "${parts[@]}"; do
  [[ -n "$result" ]] && result+="$sep"
  result+="$part"
done
echo "$result"
