packages:
  brew:
    - 1password
    - aws-sso-util
    - awscli
    - azure-cli
    - jamf/internal-tap/cloudtools
    - jamf/internal-tap/hermes
    - postman
    - slack
    - swiftbar
    - zoom
