syntax on
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

"""" Basic Behavior
set noerrorbells
set showmode!
set visualbell                  " blink cursor on error, instead of beeping
set wildmenu                    " visual autocomplete for command menu
set wildmode=longest,list,full
set ffs=unix,dos,mac

"""" Tab settings
set expandtab
set shiftwidth=2
set tabstop=2 softtabstop=2

"""" Search settings
set hlsearch
set ignorecase
set incsearch
set showmatch                   " highlight matching parenheses / brackets [{()}]
set smartcase

"""" Interface
set laststatus=2                " always show statusline
"set nowrap                      " avoid wrapping lines
set nu                          " show line numbers
set relativenumber
set ruler                       " show line and column number of the cursor on right side of statusline
set splitbelow splitright       " open new pane on the bottem and right side
set t_Co=16
set cursorline                  " highlight current line
set scrolloff=10
"set mouse+=a

"""" Files and directories
set noswapfile
set undofile
set backupdir=$XDG_DATA_HOME/vim/backup
set directory=$XDG_DATA_HOME/vim/swap
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after
set undodir=$XDG_DATA_HOME/vim/undo
set viewdir=$XDG_DATA_HOME/vim/view
set viminfo+=n$XDG_DATA_HOME/vim/viminfo

let g:netrw_home=$XDG_CACHE_HOME.'/vim'

"""" Plugins
call plug#begin('$XDG_DATA_HOME/vim/plugged')

  Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
  Plug 'junegunn/fzf.vim'
  Plug 'morhetz/gruvbox'
  Plug 'vim-airline/vim-airline'
  Plug 'vim-airline/vim-airline-themes'
  Plug 'preservim/nerdtree'
  Plug 'preservim/nerdcommenter'
  Plug 'sheerun/vim-polyglot'
  Plug 'ajh17/VimCompletesMe'
  "Plug 'yuttie/comfortable-motion.vim'
  Plug 'sheerun/vim-polyglot'

call plug#end()
nnoremap <F5> :source $MYVIMRC<CR>

au BufRead,BufNewFile *.ini set filetype=dosini
autocmd FileType vim let b:vcm_tab_complete = 'vim'

let g:airline_theme='lucius'
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1


colorscheme lucius
LuciusDark

""" NERDTree
map <C-n> :NERDTreeToggle<CR>
let NERDTreeShowHidden=1
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") && v:this_session == "" | NERDTree | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

"""" FZF shortcuts
if executable('fzf')
  " FZF {{{
  " <C-p> or <C-t> to search files
  nnoremap <silent> <C-t> :FZF -m<cr>

  " <M-p> for open buffers
  nnoremap <silent> <C-p> :Buffers<cr>

  " <M-S-p> for MRU
  nnoremap <silent> <M-S-p> :History<cr>

  " Use fuzzy completion relative filepaths across directory
  imap <expr> <c-x><c-f> fzf#vim#complete#path('git ls-files $(git rev-parse --show-toplevel)')

  " Better command history with q:
  command! CmdHist call fzf#vim#command_history({'right': '40'})
  nnoremap q: :CmdHist<CR>

  " Better search history
  command! QHist call fzf#vim#search_history({'right': '40'})
  nnoremap q/ :QHist<CR>
  " }}}
end


"""" key mappings
let mapleader = " "

inoremap hh <esc>
" Toggle line-numbers
nnoremap <F2> :set nonumber! norelativenumber!<CR>
" Toggle paste
set pastetoggle=<F3>
" Keep search results at the center of screen
nnoremap <Leader>zz :let &scrolloff=999-&scrolloff<CR>
"nmap n nzz
"nmap N Nzz
"nmap * *zz
"nmap # #zz
"nmap { {zz
"nmap } }zz
"nmap g* g*zz
"nmap g# g#zz

" Select all text
noremap vA ggVG                     "select all text

" Buffers
nnoremap <Leader>a :ls<CR>
nnoremap <Leader>h :bp<CR>
nnoremap <Leader>b :bp<CR>
nnoremap <Leader>l :bn<CR>
nnoremap <Leader>d :bd<CR>
nnoremap <Leader><Leader> :bn<CR>
nnoremap <Leader>g :e#<CR>
nnoremap <Leader>1 :1b<CR>
nnoremap <Leader>2 :2b<CR>
nnoremap <Leader>3 :3b<CR>
nnoremap <Leader>4 :4b<CR>
nnoremap <Leader>5 :5b<CR>
nnoremap <Leader>6 :6b<CR>
nnoremap <Leader>7 :7b<CR>
nnoremap <Leader>8 :8b<CR>
nnoremap <Leader>9 :9b<CR>
nnoremap <Leader>0 :10b<CR>


" Same as normal H/L behavior, but preserves scrolloff
nnoremap H :call JumpWithScrollOff('H')<CR>
nnoremap L :call JumpWithScrollOff('L')<CR>
function! JumpWithScrollOff(key) " {{{
  set scrolloff=0
  execute 'normal! ' . a:key
  set scrolloff=999
endfunction " }}}

vnoremap J :m '>+1<CR>gv=gv     
vnoremap K :m '>-2<CR>gv=gv 

