---
k9s:
  noExitOnCtrlC: false
  ui:
    logoless: true
    skin: skin
  logger:
    tail: 200
    buffer: 5000
    sinceSeconds: 300
    textWrap: false
    showTime: true
  shellPod:
    image: nicolaka/netshoot
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
