# vi: ft=tmux
###########################################################################

# Map statemate apply
bind -N "Run statemate apply" -r . confirm-before -p "Run mate apply (y/n)?" "display-popup -E -w 20% -h 20% bash -c 'mate apply --verbose; echo; read -n 1 -s -r -p \"Press any key to close...\"; echo'"
