packages:
  common:
    - age
    - git
    - less
    - lsof
    - man
    - ncdu
    - nmap
    - onefetch
    - sudo
    - tldr
    - tree
    - unzip
    - vim
    - vivid
  brew:
    - coreutils
